import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { useAuth } from '@/hooks/useAuth';
import { useDemoMode } from '@/contexts/DemoContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Building2, Shield, Eye, EyeOff, Play } from 'lucide-react';
import { toast } from '@/hooks/use-toast';

export default function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const { signIn } = useAuth();
  const { enterDemoBypass } = useDemoMode();
  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    const { error } = await signIn(email, password);

    if (error) {
      toast({
        title: 'Login Failed',
        description: error.message,
        variant: 'destructive',
      });
    } else {
      toast({
        title: 'Welcome Back',
        description: 'Successfully signed in',
      });
      navigate('/');
    }

    setLoading(false);
  };

  const handleViewDemo = () => {
    enterDemoBypass();
    toast({
      title: 'Demo Mode Activated',
      description: 'Exploring BOS with sample data as Operator',
    });
    navigate('/');
  };

  return (
    <main className="min-h-screen flex bg-background">
      {/* Left Panel - Branding */}
      <div className="hidden lg:flex lg:w-1/2 bg-gradient-to-br from-card via-background to-card p-12 flex-col justify-between border-r border-border">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-xl bg-primary flex items-center justify-center">
            <Building2 className="w-7 h-7 text-primary-foreground" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-foreground">Mi Casa Real Estate</h1>
            <p className="text-sm text-foreground/70">Brokerage Operating System</p>
          </div>
        </div>

        <div className="space-y-8">
          <div>
            <h2 className="text-3xl font-bold text-foreground mb-4">
              Production-Grade <br />
              <span className="text-primary">Real Estate Operations</span>
            </h2>
            <p className="text-foreground/75 max-w-md">
              Manage leads, deals, documents, and commissions with complete audit trails 
              and regulatory compliance built-in.
            </p>
          </div>

          <div className="grid grid-cols-2 gap-4">
            {[
              { label: 'Deterministic Workflows', desc: 'No guessing, no shortcuts' },
              { label: 'Complete Audit Trail', desc: 'Every action logged' },
              { label: 'Role-Based Access', desc: 'Secure by design' },
              { label: 'Document Automation', desc: 'Generated by workflow' },
            ].map((feature) => (
              <div key={feature.label} className="p-4 rounded-lg bg-secondary/30 border border-border">
                <p className="font-medium text-foreground text-sm">{feature.label}</p>
                <p className="text-xs text-foreground/65">{feature.desc}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="flex items-center gap-2 text-sm text-foreground/65">
          <Shield className="w-4 h-4 text-emerald" />
          <span>Abu Dhabi Licensed • DARI Compliant</span>
        </div>
      </div>

      {/* Right Panel - Login Form */}
      <div className="flex-1 flex items-center justify-center p-8">
        <div className="w-full max-w-md space-y-8">
          {/* Mobile Logo */}
          <div className="lg:hidden flex items-center justify-center gap-3 mb-8">
            <div className="w-10 h-10 rounded-lg bg-primary flex items-center justify-center">
              <Building2 className="w-5 h-5 text-primary-foreground" />
            </div>
            <span className="font-bold text-lg text-foreground">Mi Casa BOS</span>
          </div>

          <div className="text-center lg:text-left">
            <h2 className="text-2xl font-bold text-foreground">Sign in</h2>
            <p className="text-foreground/70 mt-2">
              Enter your credentials to access the system
            </p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                placeholder="you@company.ae"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
                className="h-11"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <div className="relative">
                <Input
                  id="password"
                  type={showPassword ? 'text' : 'password'}
                  placeholder="••••••••"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                  className="h-11 pr-10"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground p-2 min-w-[24px] min-h-[24px] flex items-center justify-center"
                  aria-label={showPassword ? 'Hide password' : 'Show password'}
                >
                  {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                </button>
              </div>
            </div>

            <Button
              type="submit"
              className="w-full h-11 btn-gold"
              disabled={loading}
            >
              {loading ? 'Signing in...' : 'Sign In'}
            </Button>
          </form>

          {/* Demo Mode Button */}
          <div className="relative">
            <div className="absolute inset-0 flex items-center">
              <span className="w-full border-t border-border" />
            </div>
            <div className="relative flex justify-center text-xs uppercase">
              <span className="bg-background px-2 text-foreground/60">Or</span>
            </div>
          </div>

          <Button
            type="button"
            variant="outline"
            className="w-full h-11 gap-2 border-primary/50 text-primary hover:bg-primary/10"
            onClick={handleViewDemo}
          >
            <Play className="w-4 h-4" />
            View Demo
          </Button>

          <div className="text-center text-sm">
            <span className="text-foreground/70">Don't have an account? </span>
            <Link to="/register" className="text-primary hover:underline font-medium">
              Request Access
            </Link>
          </div>

          <div className="pt-4 border-t border-border">
            <p className="text-xs text-foreground/60 text-center">
              By signing in, you agree to the system usage policies and consent 
              to activity logging for audit purposes.
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}
